version: '3.8'

services:
    # Сервис для приложения Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - ./:/var/www
        environment:
            - SERVICE_NAME=app
            - SERVICE_TAGS=dev
        networks:
            - laravel

    # Сервис для Nginx
    webserver:
        image: nginx:alpine
        container_name: laravel-webserver
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel

    # Сервис для базы данных MySQL
    db:
        image: mysql:8.0
        platform: linux/amd64
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    # Сервис для phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        container_name: laravel-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - laravel

# Определяем тома
volumes:
    dbdata:
        driver: local

# Определяем сеть
networks:
    laravel:
        driver: bridge
